### ISSUE TITLE
Inventory plugin instructions do not show required configuration changes

### ISSUE THREAD

**Issue by tadeboro** [xlab-si/steampunk.aws#6]
**Description**
Inventory plugin instructions do not show required configuration changes.

**Steps to reproduce the bug**
1. Open https://docs.steampunk.si/aws/inventory/ec2.html
2. Copy any example into the inventory file.
3. Run `ansible-inventory` as instructed.

**Expected outcome**
`ansible-inventory` should produce the output similar to the one in the documentation.

**What actually happened**
Runing `ansible-inventory` results in:

    $ ansible-inventory -i inventory.ec2.yaml --graph
    [WARNING]: Unable to parse /tmp/inventory.ec2.yaml as an inventory source
    [WARNING]: No inventory was parsed, only implicit localhost is available
    @all:
      |--@ungrouped:

**Component versions**
* Ansible version: 2.9.13 (or ansible-base 2.10.0)
* The version of the AWS Ansible Collection: 0.8.4

**Comment by mancabizjak** [comment]
The only way I'm able to _partially_ reproduce this is when the inventory plugin is missing the required authentication configuration. If you copy-pasted these examples (meaning there's no `auth` section in the inventory source file), the plugin tries to read them from the environment.

Could you please verify that you have `AWS_SECRET_KEY`, `AWS_ACCESS_KEY` and `AWS_REGION` (or alternatively: `AWS_PROFILE`) set?

Still, if this were the case, you should be able to see the warnings you're getting in combination with a message telling you what went wrong. For instance:

```
$  ansible-inventory -i inventory.ec2.yaml --graph
[WARNING]:  * Failed to parse /tmp/inventory_plugin/inventory2.ec2.yaml with
ansible_collections.steampunk.aws.plugins.inventory.ec2 plugin: The AWS profile does not specify a
default region and no region has been specified explicitly.
[WARNING]: Unable to parse /tmp/inventory_plugin/inventory2.ec2.yaml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
```

But judging from the output you provided, you don't see that (the first warning) at all.

**Comment by tadeboro** [comment]
This missing line is what is bothering me: ansible is not even trying to load the inventory config using the ec2 inventory plugin. Is there anything special on your machine that would explain the difference? I have the enterprise version of the AWS collection installed, and my configuration is clean (`ansible-config dump --only-changed` returns nothing).

**Comment by tadeboro** [comment]
I recreated the VM that I had a problem with a,nd now I cannot reproduce the problem anymore. So I guess there was something wrong with my VM.

Thanks for taking your time to check this report, @mancabizjak.
